apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend-admin
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/ascendant-altar-457900-v4/frontend-admin:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: VITE_API_URL
          value: "https://34.60.233.211/api"
        - name: VITE_BACKEND_HTTPS
          value: "https://34.60.233.211/api"
        - name: VITE_BACKEND_HTTP
          value: "https://34.60.233.211/api"
        - name: VITE_SWAGGER_URL
          value: "https://34.60.233.211/swagger"
        - name: VITE_DEV_MODE
          value: "false"
        - name: VITE_ENABLE_DEVTOOLS
          value: "false"
        - name: NODE_ENV
          value: "production"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi